# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145uIFGDVx_muvQ6uwK1ZBmZFkZtzVVe_
"""

import streamlit as st
import pytesseract
import cv2
import numpy as np
from PIL import Image

def process_receipt(image):
    image = np.array(image.convert('RGB'))
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray)
    return text

st.title("🧾 Handwritten Receipt Reader")

uploaded_file = st.file_uploader("Upload a receipt image", type=['png', 'jpg', 'jpeg'])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Receipt', use_column_width=True)

    with st.spinner("Extracting text..."):
        result = process_receipt(image)

    st.subheader("📝 Extracted Text")
    st.text_area("", result, height=300)